# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('latitude', models.FloatField(default=0.0, max_length=150)),
                ('longitude', models.FloatField(default=0.0, max_length=150)),
            ],
        ),
    ]
